"""mensaje

Revision ID: e134a8ef70a9
Revises: 
Create Date: 2020-10-06 10:01:14.792878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e134a8ef70a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_timestamp'), 'story', ['timestamp'], unique=False)
    op.create_index(op.f('ix_story_title'), 'story', ['title'], unique=True)
    op.create_table('passage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('paragraph', sa.String(length=64), nullable=True),
    sa.Column('link_1', sa.Integer(), nullable=True),
    sa.Column('link_1_text', sa.String(length=64), nullable=True),
    sa.Column('link_2', sa.Integer(), nullable=True),
    sa.Column('link_2_text', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passage_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_paragraph_id', sa.Integer(), nullable=True),
    sa.Column('link_description', sa.String(length=64), nullable=True),
    sa.Column('destination_paragraph_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_paragraph_id'], ['passage.id'], ),
    sa.ForeignKeyConstraint(['origin_paragraph_id'], ['passage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passage_link')
    op.drop_table('passage')
    op.drop_index(op.f('ix_story_title'), table_name='story')
    op.drop_index(op.f('ix_story_timestamp'), table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
